-- Create Doctor table
CREATE TABLE Doctor (
    AadharID VARCHAR2(20) PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Specialty VARCHAR2(100),
    Years_of_Experience NUMBER
);

-- Create Patient table
CREATE TABLE Patient (
    AadharID VARCHAR2(20) PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Age NUMBER,
    HouseNr VARCHAR2(20),
    StreetNr VARCHAR2(50),
    City VARCHAR2(50),
    PinCode VARCHAR2(10),
    Primary_Physician VARCHAR2(20),
    CONSTRAINT fk_primary_physician FOREIGN KEY (Primary_Physician) REFERENCES Doctor(AadharID)
);

-- Create Pharmaceutical Company table
CREATE TABLE Pharmaceutical_Company (
    Company_Name VARCHAR2(100) PRIMARY KEY,
    Phone_Number VARCHAR2(20)
);

-- Create Drug table
CREATE TABLE Drug (
    Company_Name VARCHAR2(100),
    Trade_Name VARCHAR2(100),
    Formula VARCHAR2(200),
    PRIMARY KEY (Company_Name, Trade_Name),
    CONSTRAINT fk_drug_company FOREIGN KEY (Company_Name) REFERENCES Pharmaceutical_Company(Company_Name)
);

-- Create Pharmacy table
CREATE TABLE Pharmacy (
    Name VARCHAR2(100) PRIMARY KEY,
    Building_Number VARCHAR2(20),
    Street_Number VARCHAR2(50),
    City VARCHAR2(50),
    Pin_Code VARCHAR2(10)
);

-- Create Pharmacy Phone table
CREATE TABLE Pharmacy_Phone (
    Name VARCHAR2(100),
    Phone VARCHAR2(20),
    PRIMARY KEY (Name, Phone),
    CONSTRAINT fk_pharmacy_phone FOREIGN KEY (Name) REFERENCES Pharmacy(Name)
);

CREATE TABLE Prescription (
    PrescriptionID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    PatientID VARCHAR2(12),
    DoctorID VARCHAR2(12),
    PrescDate DATE,
    UNIQUE (PatientID, DoctorID, PrescDate), -- Still enforce real-world uniqueness
    FOREIGN KEY (PatientID) REFERENCES Patient,
    FOREIGN KEY (DoctorID) REFERENCES Doctor
);


CREATE TABLE PrescriptionDrug (
    PrescriptionID NUMBER,
    TradeName VARCHAR2(100),
    CompanyName VARCHAR2(100),
    Quantity NUMBER,
    PRIMARY KEY (PrescriptionID, TradeName, CompanyName),
    FOREIGN KEY (PrescriptionID) REFERENCES Prescription.PrescriptionID,
    FOREIGN KEY (TradeName, CompanyName) REFERENCES Drug(Trade_Name, Company_Name)
);



-- Create Pharmacy-Drug Sale table
CREATE TABLE Pharmacy_Drug (
    Pharmacy_Name VARCHAR2(100),
    PharmCompany VARCHAR2(100),
    Tradename VARCHAR2(100),
    Price NUMBER,
    Quantity INT,
    PRIMARY KEY (Pharmacy_Name, PharmCompany, Tradename),
    CONSTRAINT fk_pharmacy_sale FOREIGN KEY (Pharmacy_Name) REFERENCES Pharmacy(Name),
    CONSTRAINT fk_pharma_company_sale FOREIGN KEY (PharmCompany) REFERENCES Pharmaceutical_Company(Company_Name) ON DELETE CASCADE,
    CONSTRAINT fk_drug_sale FOREIGN KEY (PharmCompany, Tradename) REFERENCES Drug(Company_Name, Trade_Name)
);

-- Create Pharmacy-Contract table
CREATE TABLE Pharmacy_Contract (
    Pharmacy_Name VARCHAR2(100),
    Company_Name VARCHAR2(100),
    Start_Date DATE,
    End_Date DATE,
    Details VARCHAR2(500),
    Supervisor VARCHAR2(100),
    PRIMARY KEY (Pharmacy_Name, Company_Name, Start_Date),
    CONSTRAINT fk_pharmacy_contract FOREIGN KEY (Pharmacy_Name) REFERENCES Pharmacy(Name),
    CONSTRAINT fk_company_contract FOREIGN KEY (Company_Name) REFERENCES Pharmaceutical_Company(Company_Name)
);

